In [5]:
# basis packages
import requests
import datetime as dt
import pandas as pd
import numpy as np
import seaborn as sea
import matplotlib.pyplot as plt
from pprint import pprint
import math
import json

# scrape packages: snscrape
import snscrape.modules.twitter as sntwitter
import itertools

In [47]:
testing = pd.read_csv("./politiker1.csv", sep=",", dtype={"likes": int})
testing

ValueError: cannot convert float NaN to integer

In [42]:
print(testing.duplicated(keep="first").sum())

105672

In [23]:
print(testing.drop_duplicates(subset='tweetID'))

       Unnamed: 0             dateTime              tweetID  \
0               0  2022-10-31 00:20:00  1586875599385235456
1               1  2022-10-29 09:59:40  1586296704047120384
2               2  2022-10-23 21:34:59  1584297357231140864
3               3  2022-10-21 20:12:20  1583551782881398785
4               4  2022-10-21 20:06:03  1583550202522513408
...           ...                  ...                  ...
265757     175012  2022-01-18 10:23:17  1483384490118594562
265758     175013  2022-01-17 10:51:20  1483029162017370115
265759     175014  2022-01-11 08:12:52  1480814957176438786
265760     175015  2022-01-08 19:31:14  1479898508954066945
265761     175016  2022-01-01 11:15:54  1477237138576003072

                                                  content  replies retweets  \
0                                              Gänsehaut.      1.0        2
1       Was @janboehm und das @zdfmagazin da gemacht h...      2.0        3
2       Palmer?! Vielleicht hätte der Kartoffelbrei da...      1.0        1
3       Der Zug wird langsamer…Jetzt Hohenzollernbrück...      6.0        1
4       So excited! In 10 min bin ich endlich wieder i...      0.0        1
...                                                   ...      ...      ...
265757  Congratulations to @RobertaMetsola for being e...      1.0      1.0
265758  Wir brauchen dringend eine Reform des EU-Asyls...      1.0      5.0
265759  Ich bin tief betroffen vom plötzlichen Tod des...      1.0      6.0
265760           @schneidercar @Eintracht 🤦🏾‍♂️🤦🏾‍♂️🤦🏾‍♂️      0.0      0.0
265761  2021 war spannend und aufregend. Ein Jahr voll...      1.0      0.0

        likes  quotes media  isRetweeted  ...  \
0         6.0     0.0   NaN          NaN  ...
1        56.0     1.0   NaN          NaN  ...
2         5.0     0.0   NaN          NaN  ...
3        19.0     0.0   NaN          NaN  ...
4         9.0     0.0   NaN          NaN  ...
...       ...     ...   ...          ...  ...
265757   13.0     0.0   NaN          NaN  ...
265758   45.0     0.0   NaN          NaN  ...
265759  175.0     0.0   NaN          NaN  ...
265760    2.0     0.0   NaN          NaN  ...
265761   54.0     0.0   NaN          NaN  ...

                          repliedTo_user  \
0                                    NaN
1                                    NaN
2                                    NaN
3                                    NaN
4                                    NaN
...                                  ...
265757                               NaN
265758                               NaN
265759                               NaN
265760  https://twitter.com/schneidercar
265761                               NaN

                                           mentionedUsers coords tweetLoc  \
0                                                     NaN    NaN      NaN
1       [User(username='janboehm', id=19072286, displa...    NaN      NaN
2                                                     NaN    NaN      NaN
3                                                     NaN    NaN      NaN
4                                                     NaN    NaN      NaN
...                                                   ...    ...      ...
265757  [User(username='RobertaMetsola', id=55031092, ...    NaN      NaN
265758  [User(username='NancyFaeser', id=620221740, di...    NaN      NaN
265759                                                NaN    NaN      NaN
265760  [User(username='schneidercar', id=96783215, di...    NaN      NaN
265761                                                NaN    NaN      NaN

                    hashtagList cashtags        user        userID  \
0                           NaN      NaN  _sanaeabdi  2.006954e+08
1                           NaN      NaN  _sanaeabdi  2.006954e+08
2                           NaN      NaN  _sanaeabdi  2.006954e+08
3                           NaN      NaN  _sanaeabdi  2.006954e+08
4       ['homeiswherethedomis']      NaN  _sanaeabdi  2.006954e+08
...                         ...      ...         ...           ...
265757                      NaN      NaN  ArmandZorn  1.313187e+18
265758                      NaN      NaN  ArmandZorn  1.313187e+18
265759                      NaN      NaN  ArmandZorn  1.313187e+18
265760                      NaN      NaN  ArmandZorn  1.313187e+18
265761                      NaN      NaN  ArmandZorn  1.313187e+18

                  userLoc  followerAmount
0                 Cologne          3691.0
1                 Cologne          3691.0
2                 Cologne          3691.0
3                 Cologne          3691.0
4                 Cologne          3691.0
...                   ...             ...
265757  Frankfurt am Main          9465.0
265758  Frankfurt am Main          9465.0
265759  Frankfurt am Main          9465.0
265760  Frankfurt am Main          9465.0
265761  Frankfurt am Main          9465.0

[147535 rows x 22 columns]

In [48]:
pd.read_csv("./politikR.csv")

,dateTime,tweetID,content,replies,retweets,likes,quotes,media,isRetweeted,isQuoted,...,repliedTo_user,mentionedUsers,coords,tweetLoc,hashtagList,cashtags,user,userID,userLoc,followerAmount
0,2022-10-31T00:20:00Z,1586875599385235456,Gänsehaut.,1,2,6,0,NaN,NaN,https://twitter.com/LulaOficial/status/1586852...,...,NaN,NaN,NaN,NaN,NaN,NaN,_sanaeabdi,2.006954e+08,Cologne,3691
1,2022-10-29T09:59:40Z,1586296704047120384,Was @janboehm und das @zdfmagazin da gemacht h...,2,3,56,1,NaN,NaN,NaN,...,NaN,"[User(username='janboehm', id=19072286, displa...",NaN,NaN,NaN,NaN,_sanaeabdi,2.006954e+08,Cologne,3691
2,2022-10-23T21:34:59Z,1584297357231140864,Palmer?! Vielleicht hätte der Kartoffelbrei da...,1,1,5,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,_sanaeabdi,2.006954e+08,Cologne,3691
3,2022-10-21T20:12:20Z,1583551782881398785,Der Zug wird langsamer…Jetzt Hohenzollernbrück...,6,1,19,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,_sanaeabdi,2.006954e+08,Cologne,3691
4,2022-10-21T20:06:03Z,1583550202522513408,So excited! In 10 min bin ich endlich wieder i...,0,1,9,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,['homeiswherethedomis'],NaN,_sanaeabdi,2.006954e+08,Cologne,3691
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175012,2022-01-18T10:23:17Z,1483384490118594562,Congratulations to @RobertaMetsola for being e...,1,1,13,0,NaN,NaN,https://twitter.com/katarinabarley/status/1483...,...,NaN,"[User(username='RobertaMetsola', id=55031092, ...",NaN,NaN,NaN,NaN,ArmandZorn,1.313187e+18,Frankfurt am Main,9465
175013,2022-01-17T10:51:20Z,1483029162017370115,Wir brauchen dringend eine Reform des EU-Asyls...,1,5,45,0,NaN,NaN,https://twitter.com/delarabur/status/148302664...,...,NaN,"[User(username='NancyFaeser', id=620221740, di...",NaN,NaN,NaN,NaN,ArmandZorn,1.313187e+18,Frankfurt am Main,9465
175014,2022-01-11T08:12:52Z,1480814957176438786,Ich bin tief betroffen vom plötzlichen Tod des...,1,6,175,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ArmandZorn,1.313187e+18,Frankfurt am Main,9465
175015,2022-01-08T19:31:14Z,1479898508954066945,@schneidercar @Eintracht 🤦🏾‍♂️🤦🏾‍♂️🤦🏾‍♂️,0,0,2,0,NaN,NaN,NaN,...,https://twitter.com/schneidercar,"[User(username='schneidercar', id=96783215, di...",NaN,NaN,NaN,NaN,ArmandZorn,1.313187e+18,Frankfurt am Main,9465
175016,2022-01-01T11:15:54Z,1477237138576003072,2021 war spannend und aufregend. Ein Jahr voll...,1,0,54,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ArmandZorn,1.313187e+18,Frankfurt am Main,9465