# Bearbeitungen der Mediendatensätze

1. Überregional
2. Regional
3. Digitale & Alternative

In [1]:
# packages
import pandas as pd
import numpy as np
from pprint import pprint
import json

## Überregionale Mediendaten

Wurden beim Scraping in zwei Wellen gewonnen.

**UPDATE: Insgesamt handelt es sich bei den überregionalen Medien um 303.573 Tweets.**

In [10]:
# laden der mediendatensätze überregional

bisPhoenix = pd.read_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/sicherung_medien_bisPhoenix.csv", encoding="UTF-8", index_col=0)
bisEnde = pd.read_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/sicherung_medien_abReuters.csv", encoding="UTF-8", index_col=0)
bisEnde

/tmp/ipykernel_23257/2444177679.py:3: DtypeWarning: Columns (14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  bisPhoenix = pd.read_csv(filepath_or_buffer="/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/sicherung_medien_bisPhoenix.csv", encoding="UTF-8", index_col=0)
/tmp/ipykernel_23257/2444177679.py:4: DtypeWarning: Columns (14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  bisEnde = pd.read_csv(filepath_or_buffer="/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/sicherung_medien_abReuters.csv", encoding="UTF-8", index_col=0)

,dateTime,tweetID,content,replies,retweets,likes,quotes,media,isRetweeted,isQuoted,...,repliedTo_user,mentionedUsers,coords,tweetLoc,hashtagList,cashtags,user,userID,userLoc,followerAmount
0,2022-01-05 10:37:36+00:00,1478677050714116098,Reuters sucht eine Finanzkorrespondentin/einen...,18,4,6,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"['journalismjobs', 'journalismus']",NaN,reuters_de,55035997,Frankfurt/Berlin,28254
1,2022-01-05 10:37:23+00:00,1478676999006740482,Für junge Newsjunkies - wir bieten ein Volonta...,8,4,8,2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"['journalismjobs', 'volontariat', 'Journalismus']",NaN,reuters_de,55035997,Frankfurt/Berlin,28254
2,2022-10-31 17:41:21+00:00,1587137665794703360,Der letzte große deutsche Warenhauskonzern #Ga...,14,2,9,2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,['GaleriaKaufhof'],NaN,RND_de,2885573171,Hannover,63801
3,2022-10-31 17:15:00+00:00,1587131033748525056,Nach dem dritten Spitzentreffen zur konzertier...,0,1,7,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"['Scholz', 'Strom', 'Gaspreisbremse']",NaN,RND_de,2885573171,Hannover,63801
4,2022-10-31 17:00:00+00:00,1587127258627571713,#Brasilien geht nach dem hauchdünnen Wahlsieg ...,0,0,3,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"['Brasilien', 'Lula']",NaN,RND_de,2885573171,Hannover,63801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192945,2022-01-01 06:37:08+00:00,1477166986593505282,Mitten in der vierten Welle der Pandemie und m...,3,3,12,0,NaN,NaN,NaN,...,NaN,"[User(username='MFratzscher', id=1374144540, d...",NaN,NaN,NaN,NaN,zeitonline,5715752,"Berlin und Hamburg, Germany",2584392
192946,2022-01-01 06:34:59+00:00,1477166443963863043,"""#Corona brachte uns etwas bei: das Aufeinande...",0,2,6,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"['Corona', 'Abo']",NaN,zeitonline,5715752,"Berlin und Hamburg, Germany",2584392
192947,2022-01-01 06:34:24+00:00,1477166296458579970,"Einheitstag, Weihnachten, erster Mai: Weil vie...",5,3,29,0,NaN,NaN,NaN,...,NaN,"[User(username='MRohwetter', id=732536808, dis...",NaN,NaN,"['Feiertage', 'Abo']",NaN,zeitonline,5715752,"Berlin und Hamburg, Germany",2584392
192948,2022-01-01 06:32:07+00:00,1477165724846198788,Wie können die nur! #Impfgegner und #Klimakris...,7,0,4,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"['Impfgegner', 'Klimakrisenleugner', 'Wissensc...",NaN,zeitonline,5715752,"Berlin und Hamburg, Germany",2584392
192949,2022-01-01 06:29:06+00:00,1477164963324219393,"Sogar Länder, die nicht in der EU sind, haben ...",2,1,12,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,['Euro'],NaN,zeitonline,5715752,"Berlin und Hamburg, Germany",2584392

In [11]:
# merge überregionaler mediendatensätze
merger = [bisPhoenix, bisEnde]
uregGes = pd.concat(merger, axis=0, ignore_index=True)
uregGes

,dateTime,tweetID,content,replies,retweets,likes,quotes,media,isRetweeted,isQuoted,...,repliedTo_user,mentionedUsers,coords,tweetLoc,hashtagList,cashtags,user,userID,userLoc,followerAmount
0,2022-10-28 08:28:39+00:00,1585911408906366977,Das ganze Interview mit Markus Söder (CSU) gib...,30,4,34,1,NaN,NaN,NaN,...,https://twitter.com/ardmoma,NaN,NaN,NaN,NaN,NaN,ardmoma,2829468550,Köln,69950
1,2022-10-28 07:07:29+00:00,1585890981483671553,Vor Beginn des #CSU-Parteitags hat der bayrisc...,90,7,104,7,[Photo(previewUrl='https://pbs.twimg.com/media...,NaN,NaN,...,NaN,"[User(username='Markus_Soeder', id=793778228, ...",NaN,NaN,"['CSU', 'Bayern']",NaN,ardmoma,2829468550,Köln,69950
2,2022-10-28 06:31:09+00:00,1585881839570403329,@andreaslahmewd @bengtbergt @markus_soeder @bu...,1,0,1,0,NaN,NaN,NaN,...,https://twitter.com/AndreasLahmeWD,"[User(username='AndreasLahmeWD', id=3982100716...",NaN,NaN,['50er'],NaN,ardmoma,2829468550,Köln,69950
3,2022-10-28 06:08:32+00:00,1585876146125934593,Immer wieder gibt es #Luftalarm in der ukraini...,2,2,9,1,[Video(thumbnailUrl='https://pbs.twimg.com/ext...,NaN,NaN,...,NaN,NaN,NaN,NaN,"['Luftalarm', 'Kiew']",NaN,ardmoma,2829468550,Köln,69950
4,2022-10-28 05:02:44+00:00,1585859588506656768,"@unattached_man: Vielen Dank, haben wir an Sve...",0,0,0,0,NaN,NaN,NaN,...,https://twitter.com/Thorns_man,NaN,NaN,NaN,NaN,NaN,ardmoma,2829468550,Köln,69950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303568,2022-01-01 06:37:08+00:00,1477166986593505282,Mitten in der vierten Welle der Pandemie und m...,3,3,12,0,NaN,NaN,NaN,...,NaN,"[User(username='MFratzscher', id=1374144540, d...",NaN,NaN,NaN,NaN,zeitonline,5715752,"Berlin und Hamburg, Germany",2584392
303569,2022-01-01 06:34:59+00:00,1477166443963863043,"""#Corona brachte uns etwas bei: das Aufeinande...",0,2,6,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"['Corona', 'Abo']",NaN,zeitonline,5715752,"Berlin und Hamburg, Germany",2584392
303570,2022-01-01 06:34:24+00:00,1477166296458579970,"Einheitstag, Weihnachten, erster Mai: Weil vie...",5,3,29,0,NaN,NaN,NaN,...,NaN,"[User(username='MRohwetter', id=732536808, dis...",NaN,NaN,"['Feiertage', 'Abo']",NaN,zeitonline,5715752,"Berlin und Hamburg, Germany",2584392
303571,2022-01-01 06:32:07+00:00,1477165724846198788,Wie können die nur! #Impfgegner und #Klimakris...,7,0,4,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"['Impfgegner', 'Klimakrisenleugner', 'Wissensc...",NaN,zeitonline,5715752,"Berlin und Hamburg, Germany",2584392
303572,2022-01-01 06:29:06+00:00,1477164963324219393,"Sogar Länder, die nicht in der EU sind, haben ...",2,1,12,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,['Euro'],NaN,zeitonline,5715752,"Berlin und Hamburg, Germany",2584392

## Regionale Mediendaten
Die Reihenfolge der CSVs, welche sich an der Liste der Zeitungen pro Bundesland orientiert, ist wie folgt:

1. regio
2. abPNP
3. abHA1725
4. abWZonline
5. abRheinpfalz
6. abGlaubeUndHeimat

Dabei Hinweis, dass bei 3. nicht HA1725 der erste Eintrag ist; hier handelt es sich einfach um einen Benennungsfehler.

**UPDATE: Insgesamt handelt es sich bei den regionalen Medien um 890.699 Tweets.**

In [20]:
# datensätze laden
regio1 = pd.read_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/sicherung_medien_regio.csv", index_col=0)
regio2 = pd.read_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/sicherung_medien_regio_abPNP.csv", index_col=0)
regio3 = pd.read_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/sicherung_medien_regio_abHA1725.csv", index_col=0)
regio4 = pd.read_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/sicherung_medien_regio_abWZonline.csv", index_col=0)
regio5 = pd.read_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/sicherung_medien_regio_abRheinpfalz.csv", index_col=0)
regio6 = pd.read_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/sicherung_medien_regio_abGlaubeUndHeimat.csv", index_col=0)

/tmp/ipykernel_23257/449830383.py:2: DtypeWarning: Columns (14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  regio1 = pd.read_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/sicherung_medien_regio.csv", index_col=0)
/tmp/ipykernel_23257/449830383.py:3: DtypeWarning: Columns (10,12,13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  regio2 = pd.read_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/sicherung_medien_regio_abPNP.csv", index_col=0)
/tmp/ipykernel_23257/449830383.py:4: DtypeWarning: Columns (10,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  regio3 = pd.read_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/sicherung_medien_regio_abHA1725.csv", index_col=0)
/tmp/ipykernel_23257/449830383.py:5: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  regio4 = pd.read_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/sicherung_medien_regio_abWZonline.csv", index_col=0)

In [22]:
# merge regionaler mediendatensätze
merger2 = [regio1,regio2,regio3,regio4,regio5,regio6]
regioGes = pd.concat(merger2, axis=0, ignore_index=True)
regioGes

,dateTime,tweetID,content,replies,retweets,likes,quotes,media,isRetweeted,isQuoted,...,repliedTo_user,mentionedUsers,coords,tweetLoc,hashtagList,cashtags,user,userID,userLoc,followerAmount
0,2022-10-31 15:11:58+00:00,1587100070507384834,Nach der vierten Niederlage in Reihe rückt die...,0,0,2,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"['kscmeineheimat', 'karlsruhersc']",NaN,BNN_BaNeuNa,806082807562960896,"Karlsruhe, Baden-Württemberg",6098
1,2022-10-31 14:25:38+00:00,1587088411839676418,Baden-Württemberg war bundesweit damit die zwe...,0,0,1,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,BNN_BaNeuNa,806082807562960896,"Karlsruhe, Baden-Württemberg",6098
2,2022-10-31 13:15:59+00:00,1587070884346531842,Bei der Landung auf dem Flugplatz in Rheinstet...,1,0,2,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,BNN_BaNeuNa,806082807562960896,"Karlsruhe, Baden-Württemberg",6098
3,2022-10-31 12:27:55+00:00,1587058786702868482,Das Ausländeramt in Rastatt ist überlastet. Au...,1,0,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,BNN_BaNeuNa,806082807562960896,"Karlsruhe, Baden-Württemberg",6098
4,2022-10-31 11:45:52+00:00,1587048203622424577,Erneut hat ein Hochzeitskorso in Karlsruhe den...,2,1,4,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,BNN_BaNeuNa,806082807562960896,"Karlsruhe, Baden-Württemberg",6098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890694,2022-01-01 15:05:19+00:00,1477294872587550720,Ein Feuerwerk an der Gedenkstätte #Buchenwald ...,0,0,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,['Buchenwald'],NaN,TLZnews,21937777,Weimar / Germany,7199
890695,2022-01-01 14:10:14+00:00,1477281011226619904,Thüringens Wirtschaftsminister Tiefensee sieht...,1,0,0,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,TLZnews,21937777,Weimar / Germany,7199
890696,2022-01-01 11:40:38+00:00,1477243363242000386,Thüringen bleibt Bundesland mit höchster Coron...,0,0,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,TLZnews,21937777,Weimar / Germany,7199
890697,2022-01-01 10:46:02+00:00,1477229621854756864,Ruhestand: Rente: Das droht jedem dritten Voll...,0,0,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,TLZnews,21937777,Weimar / Germany,7199
890698,2022-01-01 09:02:32+00:00,1477203575784751112,"Todesfall: Letztes ""Golden Girl"": Betty White ...",0,0,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,TLZnews,21937777,Weimar / Germany,7199

## Daten digitaler und alternativer Medien + ÖRR

Auch diese Daten wurden auf zwei Wellen aufgeteilt. Auch für den ÖRR gab es ein Scraping, welches auf ein Mal durchlief.

**UPDATE: Insgesamt handelt es sich bei digitalen und alternativen Medien um 89.160 Tweets. Beim ÖRR handelt es sich um 97.982 Tweets.**

In [24]:
# laden der datensätze für örr und digitale
digital1 = pd.read_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/sicherung_medien_digital1.csv", index_col=0)
digital2 = pd.read_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/sicherung_medien_digital2.csv", index_col=0)

orr = pd.read_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/sicherung_medien_orr1.csv", index_col=0)

/tmp/ipykernel_23257/2680329376.py:3: DtypeWarning: Columns (8,10) have mixed types. Specify dtype option on import or set low_memory=False.
  digital2 = pd.read_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/sicherung_medien_digital2.csv", index_col=0)

In [28]:
# merge regionaler mediendatensätze
merger3 = [digital1,digital2]
digiGes = pd.concat(merger3, axis=0, ignore_index=True)
digiGes

,dateTime,tweetID,content,replies,retweets,likes,quotes,media,isRetweeted,isQuoted,...,repliedTo_user,mentionedUsers,coords,tweetLoc,hashtagList,cashtags,user,userID,userLoc,followerAmount
0,2022-10-27 06:26:03+00:00,1585518168591695872,@CDU Seit Jahresbeginn haben Parteien insg. 10...,3,13,65,3,NaN,NaN,NaN,...,https://twitter.com/a_watch,"[User(username='CDU', id=20429858, displayname...",NaN,NaN,NaN,NaN,a_watch,35142791,Hamburg,107748
1,2022-10-26 16:57:38+00:00,1585314722261348353,Die umstrittene Klimastiftung MV möchte verhin...,4,55,129,5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,['NordStream2'],NaN,a_watch,35142791,Hamburg,107748
2,2022-10-26 16:20:51+00:00,1585305466007351296,"""Bitte gehen Sie weiter, es gibt hier nichts z...",1,19,56,0,NaN,NaN,NaN,...,NaN,"[User(username='marcelpauly', id=14646608, dis...",NaN,NaN,NaN,NaN,a_watch,35142791,Hamburg,107748
3,2022-10-26 14:52:11+00:00,1585283153664548866,+++ Großspenden-Ticker +++\n\n55.000 Euro an d...,5,50,280,1,[Photo(previewUrl='https://pbs.twimg.com/media...,NaN,NaN,...,NaN,"[User(username='CDU', id=20429858, displayname...",NaN,NaN,NaN,NaN,a_watch,35142791,Hamburg,107748
4,2022-10-26 12:44:57+00:00,1585251134804877312,Hier haben wir 2021 die Hintergründe beschrieb...,2,25,136,1,NaN,NaN,NaN,...,https://twitter.com/a_watch,"[User(username='CSU', id=21107582, displayname...",NaN,NaN,NaN,NaN,a_watch,35142791,Hamburg,107748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89155,2022-01-01 10:26:52+00:00,1477224799684468742,"""Dachte, du würdest ewig leben"": So trauern di...",0,3,6,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,WEBDENews,68724671,München,4695
89156,2022-01-01 09:51:06+00:00,1477215797370101762,Deutscher Student bei Messerstecherei in Tel A...,0,1,1,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,WEBDENews,68724671,München,4695
89157,2022-01-01 08:14:34+00:00,1477191507060871170,Drosten vorsichtig optimistisch für weitere Co...,0,0,1,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,WEBDENews,68724671,München,4695
89158,2022-01-01 07:28:32+00:00,1477179921688633344,Polizei zieht nach Silvesternacht Bilanz - Töd...,0,0,1,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,WEBDENews,68724671,München,4695
89159,2022-01-01 03:40:08+00:00,1477122441310883843,"CO2-Preis steigt, kein Ticketverkauf mehr in Z...",0,0,1,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,WEBDENews,68724671,München,4695

# Speicherung aller Datensätze als CSVs

In [31]:
uregGes.to_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/mergerDaten/uregGes.csv", encoding="utf-8")
regioGes.to_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/mergerDaten/regioGes.csv", encoding="utf-8")
digiGes.to_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/mergerDaten/digiGes.csv", encoding="utf-8")
orr.to_csv("/home/fw/Documents/uni/masterarbeit/scraping/polResp-css/mergerDaten/orr.csv", encoding="utf-8")